/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard.vehicles'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardParkRouteImport } from './routes/dashboard.park'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardFeedbackRouteImport } from './routes/dashboard.feedback'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSlotsRouteImport } from './routes/admin.slots'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/dashboard/vehicles',
  path: '/dashboard/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardParkRoute = DashboardParkRouteImport.update({
  id: '/dashboard/park',
  path: '/dashboard/park',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/dashboard/history',
  path: '/dashboard/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFeedbackRoute = DashboardFeedbackRouteImport.update({
  id: '/dashboard/feedback',
  path: '/dashboard/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/admin/vehicles',
  path: '/admin/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/admin/slots',
  path: '/admin/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/admin/records',
  path: '/admin/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/park': typeof DashboardParkRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/park': typeof DashboardParkRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/park': typeof DashboardParkRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/feedback'
    | '/admin/records'
    | '/admin/slots'
    | '/admin/users'
    | '/admin/vehicles'
    | '/dashboard/feedback'
    | '/dashboard/history'
    | '/dashboard/park'
    | '/dashboard/profile'
    | '/dashboard/vehicles'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/feedback'
    | '/admin/records'
    | '/admin/slots'
    | '/admin/users'
    | '/admin/vehicles'
    | '/dashboard/feedback'
    | '/dashboard/history'
    | '/dashboard/park'
    | '/dashboard/profile'
    | '/dashboard/vehicles'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/feedback'
    | '/admin/records'
    | '/admin/slots'
    | '/admin/users'
    | '/admin/vehicles'
    | '/dashboard/feedback'
    | '/dashboard/history'
    | '/dashboard/park'
    | '/dashboard/profile'
    | '/dashboard/vehicles'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  DashboardFeedbackRoute: typeof DashboardFeedbackRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardParkRoute: typeof DashboardParkRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/dashboard/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/park': {
      id: '/dashboard/park'
      path: '/dashboard/park'
      fullPath: '/dashboard/park'
      preLoaderRoute: typeof DashboardParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/dashboard/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/feedback': {
      id: '/dashboard/feedback'
      path: '/dashboard/feedback'
      fullPath: '/dashboard/feedback'
      preLoaderRoute: typeof DashboardFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/admin/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/admin/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  DashboardFeedbackRoute: DashboardFeedbackRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardParkRoute: DashboardParkRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardVehiclesRoute: DashboardVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
